version: '3.1'
services:
  poolstats-api-mysql:
    image: mysql:8
    environment:
      - MYSQL_USER=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=poolstats-api
    command: mysqld --lower_case_table_names=1 --skip-ssl
    ports:
      - 3306:3306
  poolstats-api:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=prod,testJobs
      - SPRING_DATASOURCE_URL=jdbc:mysql://poolstats-api-mysql:3306/poolstats-api
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8085:8080
    depends_on:
      - poolstats-api-mysql
